### PR TITLE
Update to new logo

### PR DESCRIPTION
**Pull request by ivy-lli**

### CODE REVIEW

**Comment by ivy-lli** [comment]
image

**Comment by alexsuter** [comment]
I think we need to introduce version 3?
because this container is used also on release/8.0 branches and so on.
and we also can now raise directly all extension versions. there was a major upgrade from sphinx. do you like to do that? or should I?

**Comment by ivy-lli** [comment]
In my opinion it's not bad if the new logo is also part of a new version 8 doc build...
But yes if we introduce a new version 3, we can directly raise all the sphinx versions too.

**Comment by alexsuter** [comment]
if this is not bad, then its ok for me !

**Review by alexsuter — APPROVED** [review]

**Pull request merged**
